Update cypress action version to current latest to avoid error:
    Error: Cannot find module 'cypress'
    Require stack:
    - /home/runner/work/_actions/cypress-io/github-action/v4/dist/index.js